playJava: sample.GamePlayModel Class Reference
sample.GamePlayModel Class Reference
Game play model which implements all game rules and checks for correct game play.
Public Member Functions
PlayerColor GETPlayer1Color ()
void SETGamePlayerObserver (IGamePlayObserver observer)
initializes reference gamePlayerObserver with a valid reference to the game play model events observer
void resetGameData ()
restarts the game by resetting the number of rounds to 1.
void SETPlayer1Color (PlayerColor p1color)
sets the chip color for player 1 and 2 based on selection of player 1.
void StartNewGame ()
starts a new game by resetting the board game to nulls, and reset current turn, then informs the observer to reset the view.
void ChangeStatus (Integer ColIndex) throws IOException
implements the game play rules by checking the events occur in the game when a new chip is inserted.
void SaveGameData ()
triggers game data save request to GameData model on application exit.
Static Public Member Functions
static GamePlayModel getInstance ()
creates a singleton instance of GamePlayModel if not created and returns the instance to caller.
Package Functions
void SETItsGameDataObject (GameData gameDataRef)
initializes reference itsGameData with a valid reference to the game data model
Private Member Functions
GamePlayModel ()
GamePlayModel private constructor.
int GetHighstIndexOfFreeCell (int CollIndex)
checks the first empty row in the game board based on the selected column by the current player.
boolean checkWin (int col, PlayerColor color)
checks the win conditions when a new chip is inserted in the game board.
boolean checkDiagonal (int row, int col, PlayerColor color, boolean rightDiagonal)
checks the win conditions when a new chip is inserted in the game board in the diagonals.
Private Attributes
PlayerColor Player1Color
Player 1 color selected in the color selection controller.
PlayerColor Player2Color
Player 2 color selected in the color selection controller.
int Player1CurrentScore
loaded from GameData during startup and incremented with each player 1 game win
int Player2CurrentScore
loaded from GameData during startup and incremented with each player 2 game win
int ColumnsCount = 7
Number of columns in the game board.
int RowsCount = 6
Number of rows in the game board.
int round = 1
Game round, incremented with each game win.
boolean IsCurrentTurnPlayer1
flag to check if the current turn is for player 1 or 2
PlayerColor BoardGrid [][]
The game play board showing which cells are empty or full, and with which color.
GameData itsGameData
Reference to the GameData model.
IGamePlayObserver gamePlayerObserver = null
Reference to the game board controller as observer to the model events.
Static Private Attributes
static GamePlayModel myOnlyObject = null
Instance reference of the singleton pattern.
Detailed Description
Game play model which implements all game rules and checks for correct game play.
GamePlayModel is implemented as Singleton design pattern, Singleton means that the object is created only once and used by many other classes Check the following link https://www.geeksforgeeks.org/singleton-class-java
We have created here the GamePlayModel as Singleton class. The Class will have a static reference to single instance. There reference is initialized to null. The constructor and the instance reference will be private so that no other one outside the class can create an instance. There will be a function called getInstance, the function will be defined as public static, so that anyone outside the class can call it. When the function is called for the first time in the code it will create an instance. Then each time the function is called again it will return the created instance during the first time.
Definition at line 21 of file GamePlayModel.java.
Constructor & Destructor Documentation
GamePlayModel()
sample.GamePlayModel.GamePlayModel () private
GamePlayModel private constructor.
The constructor is created private to disallow any external class to instantiate an object of the GameData class so that the class can be created only once, a singleton. It initializes the game play data as well.
Definition at line 40 of file GamePlayModel.java.
{
         Player1Color = null;
         Player2Color = null;
     }
References sample.GamePlayModel.Player1Color, and sample.GamePlayModel.Player2Color.
Referenced by sample.GamePlayModel.getInstance().
Member Function Documentation
ChangeStatus()
void sample.GamePlayModel.ChangeStatus (Integer ColIndex) throws IOException
implements the game play rules by checking the events occur in the game when a new chip is inserted.
This method is called by the BoardController when one of the player inserts a new chip on the board.
This is the core function for the game play, performs the following steps
1) Gets the location of the inserted chip on the board
1a) takes as an argument the column selected by the user and checks the first empty row on the board
1b) if the column is full or the column index is invalid the method terminates
2) checks the current turn
3) if the current turn is for player 1, it colors the current cell with player 1 color, else it uses player 2 color
4) notifies the BoardController to update the view the current player color
5) checks if the current chip can cause a win situation, if win condition is true
5a) increments the score of the current player
5b) notifies the BoardController to update the view to show win situation for current player
5c) update the GameData model with the new score for player 1 and 2
6) if there no win condition, then changes the turn to the other player
7) notifies the BoardController to update the view to change the turn to the other player
Parameters
ColIndex index of the column selected by the current player
Definition at line 162 of file GamePlayModel.java.
{
         if (ColIndex == null) ColIndex = 0;
         Integer RowIndex = 0;
         if (ColIndex >= ColumnsCount) return;
         RowIndex = GetHighstIndexOfFreeCell(ColIndex);
         if (RowIndex != -1) {
             if (IsCurrentTurnPlayer1) {
                 BoardGrid[RowIndex][ColIndex] = Player1Color;
                 if (null != gamePlayerObserver)
                     gamePlayerObserver.SETCellColor(ColIndex, RowIndex, Player1Color);
                 boolean IsWin = checkWin (ColIndex, Player1Color);
                 if(IsWin){
                     Player1CurrentScore++;
                     if (null != gamePlayerObserver)
                         gamePlayerObserver.PrintIfWin();
                     itsGameData.updateGameData(Player1CurrentScore, Player2CurrentScore);
                 }
             } else {
                 BoardGrid[RowIndex][ColIndex] = Player2Color;
                 if (null != gamePlayerObserver)
                     gamePlayerObserver.SETCellColor(ColIndex, RowIndex, Player2Color);
                 boolean IsWin = checkWin (ColIndex, Player2Color);
                 if(IsWin){
                     Player2CurrentScore++;
                     if (null != gamePlayerObserver)
                         gamePlayerObserver.PrintIfWin();
                     itsGameData.updateGameData(Player1CurrentScore, Player2CurrentScore);
                 }
             }
 //change turn and color of the turn circle
             IsCurrentTurnPlayer1 = !IsCurrentTurnPlayer1;
             if (null != gamePlayerObserver)
                 gamePlayerObserver.SETIsPlayer1CurrentTurn(IsCurrentTurnPlayer1);
         }
     }
References sample.GamePlayModel.BoardGrid, sample.GamePlayModel.checkWin(), sample.GamePlayModel.ColumnsCount, sample.GamePlayModel.gamePlayerObserver, sample.GamePlayModel.GetHighstIndexOfFreeCell(), sample.GamePlayModel.IsCurrentTurnPlayer1, sample.GamePlayModel.itsGameData, sample.GamePlayModel.Player1Color, sample.GamePlayModel.Player1CurrentScore, sample.GamePlayModel.Player2Color, sample.GamePlayModel.Player2CurrentScore, sample.IGamePlayObserver.PrintIfWin(), sample.IGamePlayObserver.SETCellColor(), sample.IGamePlayObserver.SETIsPlayer1CurrentTurn(), and sample.GameData.updateGameData().
Referenced by sample.BoardController.cellClicked().
checkDiagonal()
boolean sample.GamePlayModel.checkDiagonal (int row, int col, PlayerColor color, boolean rightDiagonal) private
checks the win conditions when a new chip is inserted in the game board in the diagonals.
the function can be used for right diagonal or the left diagonal through the parameter rightDiagonal. In the diagonal check the row and column are incremented by 1 on each check step. In the right diagonal the column is increment towards the last column, if left diagonal then the column is decremented towards the first column. The reverser variable is used to either increment or decrement the index of the checked column. checkDiagonal performs the following steps
1) checks the diagonal direction and sets reverser value based on that
1a) if right diagonal then reverser is set to 1, else reverser is set to -1
2) loops on the cells starting from (current chip row + 3, current chip column + 3) to (current chip row - 3, current chip column - 3)
2a) if 4 chips are found in sequence of the same color of the current player then it is a win condition
3) if no win condition detected at all then return false
Parameters
col the current column in which the chip is inserted.
row the current row in which the chip is inserted.
color color of the current player
rightDiagonal flag to check whether we are checking the right diagonal or left diagonal
Returns
true if win condition is detected, false otherwise
Definition at line 298 of file GamePlayModel.java.
{
         int winningStreak = 4;
         int rows = RowsCount;
         int columns = ColumnsCount;
         int reverser;
         if (rightDiagonal) reverser = 1; else reverser = -1;
         for(int winRow = row + 3, winCol = col - (3 * reverser); winRow >= row - 3; winRow--, winCol += reverser) {
             if (!rightDiagonal) {
                 if (winRow < 0 || winCol < 0) continue;
                 if (winRow >= rows || winCol >= columns) break;
             } else {
                 if(winRow < 0 || winCol >= columns) continue;
                 if(winRow >= rows || winCol < 0) break;
             }
             if(BoardGrid[winRow][winCol] != null && BoardGrid[winRow][winCol]== color) {
                 winningStreak--;
                 if (winningStreak == 0) return true;
             } else winningStreak = 4;
         }
         return false;
     }
References sample.GamePlayModel.BoardGrid, sample.GamePlayModel.ColumnsCount, and sample.GamePlayModel.RowsCount.
Referenced by sample.GamePlayModel.checkWin().
checkWin()
boolean sample.GamePlayModel.checkWin (int col, PlayerColor color) private
checks the win conditions when a new chip is inserted in the game board.
performs the following steps
1) checks the vertical win condition, checks the selected column by the current player
1a) checks if 3 chips below the inserted chip are of the same color as the new chip then win condition is true
2) checks horizontal win condition, checks if the row in which the chip is inserted has a win condition
2a) checks 3 chips before the inserted chips and 3 chips after the inserted chip
2b) if 4 chips are found in row of the same color of the current player then it is a win condition
3) if no win condition detected, then check the right diagonal and the left diagonal
7) if no win condition detected at all then return false
Parameters
col the current column in which the chip is inserted.
color color of the current player
Returns
true if win condition is detected, false otherwise
Definition at line 243 of file GamePlayModel.java.
{
         int rows = RowsCount;
         int columns = ColumnsCount;
         for(int row = 0; row < rows; row++) {
             if(BoardGrid[row][col] != null) {
                 // if this reaches 0, we have won
                 int winningNumber = 3;
                 // check downwards
                 for(int winRow = row + 1; winRow < rows; winRow++) {
                     if(BoardGrid[winRow][col] == color) {
                         winningNumber--;
                         if(winningNumber == 0) return true;
                     } else winningNumber = 3;
                 }
                 winningNumber = 4;
                 // look at the horizontal
                 for(int winCol = col - 3; winCol <= col + 3; winCol++) {
                     if(winCol < 0) continue; // if the column number is not valid then skip the current loop and continue to the next column
                     if(winCol >= columns) break; // if the column number exceeded the board limits then break the loop
                     if(BoardGrid[row][winCol] != null && BoardGrid[row][winCol]== color) {
                         winningNumber--;
                         if(winningNumber == 0) return true;
                     } else winningNumber = 4;
                 }
                 if(checkDiagonal(row, col, color, false)) return true;
                 if(checkDiagonal(row, col, color, true)) return true;
                 return false;
             }
         }
         return false;
     }
References sample.GamePlayModel.BoardGrid, sample.GamePlayModel.checkDiagonal(), sample.GamePlayModel.ColumnsCount, and sample.GamePlayModel.RowsCount.
Referenced by sample.GamePlayModel.ChangeStatus().
GetHighstIndexOfFreeCell()
int sample.GamePlayModel.GetHighstIndexOfFreeCell (int CollIndex) private
checks the first empty row in the game board based on the selected column by the current player.
Parameters
CollIndex index of the selected column by the current player.
Definition at line 220 of file GamePlayModel.java.
{
         for(int i = RowsCount - 1; i >= 0 ; i--){
             if(BoardGrid[i][CollIndex] == null){
                 return i;
             }
         }
         return -1;
     }
References sample.GamePlayModel.BoardGrid, and sample.GamePlayModel.RowsCount.
Referenced by sample.GamePlayModel.ChangeStatus().
getInstance()
static GamePlayModel sample.GamePlayModel.getInstance () static
creates a singleton instance of GamePlayModel if not created and returns the instance to caller.
Returns
The singleton instance of GamePlayModel class
Definition at line 64 of file GamePlayModel.java.
     {
         if (myOnlyObject == null)
             myOnlyObject = new GamePlayModel();
         return myOnlyObject;
     }
References sample.GamePlayModel.GamePlayModel(), and sample.GamePlayModel.myOnlyObject.
Referenced by sample.BoardController.BoardController(), sample.Controller.Controller(), sample.MenuController.MenuController(), sample.PlayAgainController.PlayAgainController(), sample.Main.start(), sample.UserOneController.UserOneController(), and sample.UserTwoController.UserTwoController().
GETPlayer1Color()
PlayerColor sample.GamePlayModel.GETPlayer1Color ()
Returns
player 1 color
Definition at line 48 of file GamePlayModel.java.
{
         return Player1Color;
     }
References sample.GamePlayModel.Player1Color.
Referenced by sample.BoardController.initialize(), sample.UserTwoController.initialize(), and sample.BoardController.SETIsPlayer1CurrentTurn().
resetGameData()
void sample.GamePlayModel.resetGameData ()
restarts the game by resetting the number of rounds to 1.
This method is called by the BoardController to reset the game play.
Definition at line 84 of file GamePlayModel.java.
{
         round = 1;
     }
References sample.GamePlayModel.round.
Referenced by sample.BoardController.showMenu().
SaveGameData()
void sample.GamePlayModel.SaveGameData ()
triggers game data save request to GameData model on application exit.
Definition at line 211 of file GamePlayModel.java.
{
         itsGameData.updateGameData(Player1CurrentScore, Player2CurrentScore);
         itsGameData.saveGameData();
     }
References sample.GamePlayModel.itsGameData, sample.GamePlayModel.Player1CurrentScore, sample.GamePlayModel.Player2CurrentScore, sample.GameData.saveGameData(), and sample.GameData.updateGameData().
Referenced by sample.MenuController.exit(), sample.Controller.exit(), and sample.PlayAgainController.exitGame().
SETGamePlayerObserver()
void sample.GamePlayModel.SETGamePlayerObserver (IGamePlayObserver observer)
initializes reference gamePlayerObserver with a valid reference to the game play model events observer
Parameters
observer a valid reference to the game play model events observer
Definition at line 76 of file GamePlayModel.java.
{
         gamePlayerObserver = observer;
     }
References sample.GamePlayModel.gamePlayerObserver.
Referenced by sample.BoardController.initialize().
SETItsGameDataObject()
void sample.GamePlayModel.SETItsGameDataObject (GameData gameDataRef) package
initializes reference itsGameData with a valid reference to the game data model
Parameters
gameDataRef a valid reference to the game data model
Definition at line 56 of file GamePlayModel.java.
{
         itsGameData = gameDataRef;
     }
References sample.GamePlayModel.itsGameData.
Referenced by sample.Main.start().
SETPlayer1Color()
void sample.GamePlayModel.SETPlayer1Color (PlayerColor p1color)
sets the chip color for player 1 and 2 based on selection of player 1.
This method is called by the UserOneController to set the color for player 1. Available game colors are yellow and red. If player 1 has selected red then player 2 will automatically be assigned to yellow and vice verse.
Parameters
p1color color selected by player 1
Definition at line 95 of file GamePlayModel.java.
{
         switch (p1color) {
             case YELLOW:
                 Player1Color = PlayerColor.YELLOW;
                 Player2Color = PlayerColor.RED;
                 break;
             case RED:
                 Player1Color = PlayerColor.RED;
                 Player2Color = PlayerColor.YELLOW;
                 break;
             default:
                 Player1Color = null;
                 Player2Color = null;
                 break;
         }
         if (Player1Color == PlayerColor.RED) {
             System.out.println("Player 1 color is RED");
             System.out.println("Player 2 color is YELLOW");
         } else if (Player1Color == PlayerColor.YELLOW) {
             System.out.println("Player 1 color is YELLOW");
             System.out.println("Player 2 color is RED");
         }
     }
References sample.GamePlayModel.Player1Color, sample.GamePlayModel.Player2Color, sample.PlayerColor.RED, and sample.PlayerColor.YELLOW.
Referenced by sample.UserOneController.chooseRed(), and sample.UserOneController.chooseYellow().
StartNewGame()
void sample.GamePlayModel.StartNewGame ()
starts a new game by resetting the board game to nulls, and reset current turn, then informs the observer to reset the view.
This method is called by the BoardController to start a new game without resetting the game play.
The function performs the following steps
1) creates a new board game with all cells empty.
2) reset the current turn to be for player 1.
3) notifies the BoardController to update view that current turn is for player 1.
4) notifies the BoardController to update view with the new round value, player 1 score, and player 2 score.
Definition at line 131 of file GamePlayModel.java.
{
         BoardGrid = new PlayerColor[RowsCount][ColumnsCount];
         // initialize Turn
         IsCurrentTurnPlayer1 = true;
         if (null != gamePlayerObserver) {
             gamePlayerObserver.SETIsPlayer1CurrentTurn(true);
             gamePlayerObserver.updateGameData(round, Player1CurrentScore, Player2CurrentScore);
         }
         round++;
      }
References sample.GamePlayModel.BoardGrid, sample.GamePlayModel.ColumnsCount, sample.GamePlayModel.gamePlayerObserver, sample.GamePlayModel.IsCurrentTurnPlayer1, sample.GamePlayModel.Player1CurrentScore, sample.GamePlayModel.Player2CurrentScore, sample.GamePlayModel.round, sample.GamePlayModel.RowsCount, sample.IGamePlayObserver.SETIsPlayer1CurrentTurn(), and sample.IGamePlayObserver.updateGameData().
Referenced by sample.BoardController.initialize().
Member Data Documentation
BoardGrid
PlayerColor sample.GamePlayModel.BoardGrid[][] private
The game play board showing which cells are empty or full, and with which color.
Definition at line 31 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), sample.GamePlayModel.checkDiagonal(), sample.GamePlayModel.checkWin(), sample.GamePlayModel.GetHighstIndexOfFreeCell(), and sample.GamePlayModel.StartNewGame().
ColumnsCount
int sample.GamePlayModel.ColumnsCount = 7 private
Number of columns in the game board.
Definition at line 27 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), sample.GamePlayModel.checkDiagonal(), sample.GamePlayModel.checkWin(), and sample.GamePlayModel.StartNewGame().
gamePlayerObserver
IGamePlayObserver sample.GamePlayModel.gamePlayerObserver = null private
Reference to the game board controller as observer to the model events.
Definition at line 33 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), sample.GamePlayModel.SETGamePlayerObserver(), and sample.GamePlayModel.StartNewGame().
IsCurrentTurnPlayer1
boolean sample.GamePlayModel.IsCurrentTurnPlayer1 private
flag to check if the current turn is for player 1 or 2
Definition at line 30 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), and sample.GamePlayModel.StartNewGame().
itsGameData
GameData sample.GamePlayModel.itsGameData private
Reference to the GameData model.
Definition at line 32 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), sample.GamePlayModel.SaveGameData(), and sample.GamePlayModel.SETItsGameDataObject().
myOnlyObject
GamePlayModel sample.GamePlayModel.myOnlyObject = null static private
Instance reference of the singleton pattern.
Definition at line 22 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.getInstance().
Player1Color
PlayerColor sample.GamePlayModel.Player1Color private
Player 1 color selected in the color selection controller.
Definition at line 23 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), sample.GamePlayModel.GamePlayModel(), sample.GamePlayModel.GETPlayer1Color(), and sample.GamePlayModel.SETPlayer1Color().
Player1CurrentScore
int sample.GamePlayModel.Player1CurrentScore private
loaded from GameData during startup and incremented with each player 1 game win
Definition at line 25 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), sample.GamePlayModel.SaveGameData(), and sample.GamePlayModel.StartNewGame().
Player2Color
PlayerColor sample.GamePlayModel.Player2Color private
Player 2 color selected in the color selection controller.
Definition at line 24 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), sample.GamePlayModel.GamePlayModel(), and sample.GamePlayModel.SETPlayer1Color().
Player2CurrentScore
int sample.GamePlayModel.Player2CurrentScore private
loaded from GameData during startup and incremented with each player 2 game win
Definition at line 26 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.ChangeStatus(), sample.GamePlayModel.SaveGameData(), and sample.GamePlayModel.StartNewGame().
round
int sample.GamePlayModel.round = 1 private
Game round, incremented with each game win.
Definition at line 29 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.resetGameData(), and sample.GamePlayModel.StartNewGame().
RowsCount
int sample.GamePlayModel.RowsCount = 6 private
Number of rows in the game board.
Definition at line 28 of file GamePlayModel.java.
Referenced by sample.GamePlayModel.checkDiagonal(), sample.GamePlayModel.checkWin(), sample.GamePlayModel.GetHighstIndexOfFreeCell(), and sample.GamePlayModel.StartNewGame().
The documentation for this class was generated from the following file:
C:/master/PatternsUndFrameworks/playJava/src/sample/GamePlayModel.java