playJava: sample.IGamePlayObserver Interface Reference
sample.IGamePlayObserver Interface Reference
game play model observer interface.
Public Member Functions
void SETIsPlayer1CurrentTurn (boolean isPlayer1CurrTurn)
void updateGameData (int round, int p1score, int p2score)
void SETCellColor (Integer ColIndex, Integer RowIndex, PlayerColor cellColor)
void PrintIfWin () throws IOException
Detailed Description
game play model observer interface.
interface can not make objects so we implement the interface in a class that can make object
Definition at line 9 of file IGamePlayObserver.java.
Member Function Documentation
PrintIfWin()
void sample.IGamePlayObserver.PrintIfWin () throws IOException
Implemented in sample.BoardController.
Referenced by sample.GamePlayModel.ChangeStatus().
SETCellColor()
void sample.IGamePlayObserver.SETCellColor (Integer ColIndex, Integer RowIndex, PlayerColor cellColor)
Implemented in sample.BoardController.
Referenced by sample.GamePlayModel.ChangeStatus().
SETIsPlayer1CurrentTurn()
void sample.IGamePlayObserver.SETIsPlayer1CurrentTurn (boolean isPlayer1CurrTurn)
Implemented in sample.BoardController.
Referenced by sample.GamePlayModel.ChangeStatus(), and sample.GamePlayModel.StartNewGame().
updateGameData()
void sample.IGamePlayObserver.updateGameData (int round, int p1score, int p2score)
Implemented in sample.BoardController.
Referenced by sample.GamePlayModel.StartNewGame().
The documentation for this interface was generated from the following file:
C:/master/PatternsUndFrameworks/playJava/src/sample/IGamePlayObserver.java