playJava: sample.AccountController Class Reference
sample.AccountController Class Reference
Public Member Functions
AccountController ()
void initialize ()
void showMenu (javafx.event.ActionEvent actionEvent) throws IOException
Private Attributes
AnchorPane rootPane
TextField user1Name
GameData itsData
TextField p1HighestScore
TextField p1LastScore
TextField p2HighestScore
TextField p2LastScore
Detailed Description
Definition at line 7 of file AccountController.java.
Constructor & Destructor Documentation
AccountController()
sample.AccountController.AccountController ()
Definition at line 23 of file AccountController.java.
{
         itsData = GameData.getInstance();
     }
References sample.GameData.getInstance(), and sample.AccountController.itsData.
Member Function Documentation
initialize()
void sample.AccountController.initialize ()
Definition at line 28 of file AccountController.java.
{
         Score score = itsData.GETPlayer1Score();
         p1HighestScore.setText(Integer.toString(score.getPlayerHighestScore()));
         p1LastScore.setText(Integer.toString(score.getPlayerLastScore()));
         score = itsData.GETPlayer2Score();
         p2HighestScore.setText(Integer.toString(score.getPlayerHighestScore()));
         p2LastScore.setText(Integer.toString(score.getPlayerLastScore()));
     }
References sample.GameData.GETPlayer1Score(), sample.GameData.GETPlayer2Score(), sample.Score.getPlayerHighestScore(), sample.Score.getPlayerLastScore(), sample.AccountController.itsData, sample.AccountController.p1HighestScore, sample.AccountController.p1LastScore, sample.AccountController.p2HighestScore, and sample.AccountController.p2LastScore.
showMenu()
void sample.AccountController.showMenu (javafx.event.ActionEvent actionEvent) throws IOException
Definition at line 38 of file AccountController.java.
{
         try {
             AnchorPane pane = FXMLLoader.load(getClass().getResource("menu.fxml"));
             rootPane.getChildren().setAll(pane);
         } catch (Exception e) {
             System.out.println(e);
         }
     }
References sample.AccountController.rootPane.
Member Data Documentation
itsData
GameData sample.AccountController.itsData private
Definition at line 13 of file AccountController.java.
Referenced by sample.AccountController.AccountController(), and sample.AccountController.initialize().
p1HighestScore
TextField sample.AccountController.p1HighestScore private
Definition at line 15 of file AccountController.java.
Referenced by sample.AccountController.initialize().
p1LastScore
TextField sample.AccountController.p1LastScore private
Definition at line 17 of file AccountController.java.
Referenced by sample.AccountController.initialize().
p2HighestScore
TextField sample.AccountController.p2HighestScore private
Definition at line 19 of file AccountController.java.
Referenced by sample.AccountController.initialize().
p2LastScore
TextField sample.AccountController.p2LastScore private
Definition at line 21 of file AccountController.java.
Referenced by sample.AccountController.initialize().
rootPane
AnchorPane sample.AccountController.rootPane private
Definition at line 10 of file AccountController.java.
Referenced by sample.AccountController.showMenu().
user1Name
TextField sample.AccountController.user1Name private
Definition at line 12 of file AccountController.java.
The documentation for this class was generated from the following file:
C:/master/PatternsUndFrameworks/playJava/src/sample/AccountController.java