playJava: sample.GameData Class Reference
sample.GameData Class Reference
model class to save and load game data on HDD.
Public Member Functions
void loadGameData () throws FileNotFoundException
loads the game data from the HDD.
void updateGameData (int P1CurrScore, int P2CurrScore)
updates the game data with the current score of player 1 and player 2.
void saveGameData ()
saves player 1 and player 2 data to the HDD.
Score GETPlayer1Score ()
returns player 1 last score and highest score in meta-class score.
Score GETPlayer2Score ()
returns player 2 last score and highest score in meta-class score.
Static Public Member Functions
static GameData getInstance ()
creates a singleton instance of GameData if not created and returns the instance to caller.
Private Member Functions
GameData ()
GameData private constructor.
Private Attributes
int player1LastScore
Player 1 last score.
int player2LastScore
Player 2 last score.
int player1HighestScore
Player 1 highest score.
int player2HighestScore
Player 2 highest score.
String filepath = "Data1"
Path to the data file holding the game data stored on the hdd.
Static Private Attributes
static GameData mySingletonInstance = null
Instance reference of the singleton pattern.
Detailed Description
model class to save and load game data on HDD.
The class is implemented as singleton pattern, to allow single game data model in the whole game. Also this allows accessing the game data model reference from any other class.
Definition at line 13 of file GameData.java.
Constructor & Destructor Documentation
GameData()
sample.GameData.GameData () private
GameData private constructor.
The constructor is created private to disallow any external class to instantiate an object of the GameData class so that the class can be created only once, a singleton.
Definition at line 27 of file GameData.java.
 { }
Referenced by sample.GameData.getInstance().
Member Function Documentation
getInstance()
static GameData sample.GameData.getInstance () static
creates a singleton instance of GameData if not created and returns the instance to caller.
Returns
The singleton instance of GameData class
Definition at line 33 of file GameData.java.
{
         if (mySingletonInstance == null)
             mySingletonInstance = new GameData();
         return mySingletonInstance;
     }
References sample.GameData.GameData(), and sample.GameData.mySingletonInstance.
Referenced by sample.AccountController.AccountController(), and sample.Main.start().
GETPlayer1Score()
Score sample.GameData.GETPlayer1Score ()
returns player 1 last score and highest score in meta-class score.
See also
// https://stackoverflow.com/questions/2832472/how-to-return-2-values-from-a-java-method
Returns
Object of meta-class score contains player 1 last and highest score
Definition at line 124 of file GameData.java.
{
         return new Score(player1LastScore, player1HighestScore);
     }
References sample.GameData.player1HighestScore, and sample.GameData.player1LastScore.
Referenced by sample.AccountController.initialize().
GETPlayer2Score()
Score sample.GameData.GETPlayer2Score ()
returns player 2 last score and highest score in meta-class score.
See also
// https://stackoverflow.com/questions/2832472/how-to-return-2-values-from-a-java-method
Returns
Object of meta-class score contains player 2 last and highest score
Definition at line 133 of file GameData.java.
{
         return new Score(player2LastScore, player2HighestScore);
     }
References sample.GameData.player2HighestScore, and sample.GameData.player2LastScore.
Referenced by sample.AccountController.initialize().
loadGameData()
void sample.GameData.loadGameData () throws FileNotFoundException
loads the game data from the HDD.
If the game data file is not created, it creates a new one with empty data. If the game data file is existing it reads the stored data.
Definition at line 45 of file GameData.java.
{
         try {
             File Data1 = new File(filepath);
             String absolute = Data1.getAbsolutePath();
             System.out.println("Loading system data from file: " + absolute);
             if (!Data1.exists()) {
                 if (!Data1.createNewFile()) {
                     System.out.println("Failed to create a game data file");
                     return;
                 }
                 FileWriter myWriter = new FileWriter(Data1, true);
                 myWriter.write(String.valueOf(player1LastScore) + "\n"); // Player 1 Last Score
                 myWriter.write(String.valueOf(player2LastScore) + "\n"); // Player 2 Last Score
                 myWriter.write(String.valueOf(player1HighestScore) + "\n"); // Player 1 Highest Score
                 myWriter.write(String.valueOf(player2HighestScore) + "\n"); // Player 2 Highest Score
                 myWriter.close();
                 return;
             }
             Scanner myReader = new Scanner(Data1);
             player1LastScore = myReader.nextInt();
             player2LastScore = myReader.nextInt();
             player1HighestScore = myReader.nextInt();
             player2HighestScore = myReader.nextInt();
             //System.out.println(player1HighestScore);
             myReader.close();
         } catch (Exception e) {
         }
     }
References sample.GameData.filepath, sample.GameData.player1HighestScore, sample.GameData.player1LastScore, sample.GameData.player2HighestScore, and sample.GameData.player2LastScore.
Referenced by sample.Main.start().
saveGameData()
void sample.GameData.saveGameData ()
saves player 1 and player 2 data to the HDD.
Definition at line 102 of file GameData.java.
{
         try {
             File Data1 = new File(filepath);
             String absolute = Data1.getAbsolutePath();
             System.out.println("Saving system data to file: " + absolute);
             FileWriter myWriter = new FileWriter(Data1);
             myWriter.write(String.valueOf(player1LastScore) + "\n"); // Player 1 Last Score
             myWriter.write(String.valueOf(player2LastScore) + "\n"); // Player 2 Last Score
             myWriter.write(String.valueOf(player1HighestScore) + "\n"); // Player 1 Highest Score
             myWriter.write(String.valueOf(player2HighestScore) + "\n"); // Player 2 Highest Score
             myWriter.close();
         } catch (Exception e) {
         }
     }
References sample.GameData.filepath, sample.GameData.player1HighestScore, sample.GameData.player1LastScore, sample.GameData.player2HighestScore, and sample.GameData.player2LastScore.
Referenced by sample.GamePlayModel.SaveGameData().
updateGameData()
void sample.GameData.updateGameData (int P1CurrScore, int P2CurrScore)
updates the game data with the current score of player 1 and player 2.
If player 1 current score is greater than highest score it updates the last score with the current score, same for player 2. And then it stores player 1 and 2 current score as the last score.
Parameters
P1CurrScore player 1 current score as stored in the game model.
P1CurrScore player 2 current score as stored in the game model.
Definition at line 88 of file GameData.java.
{
         player1LastScore = P1CurrScore ;
         player2LastScore = P2CurrScore;
         if(P1CurrScore > player1HighestScore){
             player1HighestScore = P1CurrScore;
         }
         if(P2CurrScore > player2HighestScore){
             player2HighestScore = P2CurrScore;
         }
     }
References sample.GameData.player1HighestScore, sample.GameData.player1LastScore, sample.GameData.player2HighestScore, and sample.GameData.player2LastScore.
Referenced by sample.GamePlayModel.ChangeStatus(), and sample.GamePlayModel.SaveGameData().
Member Data Documentation
filepath
String sample.GameData.filepath = "Data1" private
Path to the data file holding the game data stored on the hdd.
Definition at line 19 of file GameData.java.
Referenced by sample.GameData.loadGameData(), and sample.GameData.saveGameData().
mySingletonInstance
GameData sample.GameData.mySingletonInstance = null static private
Instance reference of the singleton pattern.
Definition at line 14 of file GameData.java.
Referenced by sample.GameData.getInstance().
player1HighestScore
int sample.GameData.player1HighestScore private
Player 1 highest score.
Definition at line 17 of file GameData.java.
Referenced by sample.GameData.GETPlayer1Score(), sample.GameData.loadGameData(), sample.GameData.saveGameData(), and sample.GameData.updateGameData().
player1LastScore
int sample.GameData.player1LastScore private
Player 1 last score.
Definition at line 15 of file GameData.java.
Referenced by sample.GameData.GETPlayer1Score(), sample.GameData.loadGameData(), sample.GameData.saveGameData(), and sample.GameData.updateGameData().
player2HighestScore
int sample.GameData.player2HighestScore private
Player 2 highest score.
Definition at line 18 of file GameData.java.
Referenced by sample.GameData.GETPlayer2Score(), sample.GameData.loadGameData(), sample.GameData.saveGameData(), and sample.GameData.updateGameData().
player2LastScore
int sample.GameData.player2LastScore private
Player 2 last score.
Definition at line 16 of file GameData.java.
Referenced by sample.GameData.GETPlayer2Score(), sample.GameData.loadGameData(), sample.GameData.saveGameData(), and sample.GameData.updateGameData().
The documentation for this class was generated from the following file:
C:/master/PatternsUndFrameworks/playJava/src/sample/GameData.java