playJava: sample.BoardController Class Reference
sample.BoardController Class Reference
Public Member Functions
BoardController ()
void initialize ()
void showMenu (javafx.event.ActionEvent actionEvent) throws IOException
void cellClicked (javafx.scene.input.MouseEvent e)
void SETIsPlayer1CurrentTurn (boolean isPlayer1CurrTurn)
Node getNodeByRowColumnIndex (Integer ColIndex, Integer RowIndex)
void SETCellColor (Integer ColIndex, Integer RowIndex, PlayerColor cellColor)
void PrintIfWin () throws IOException
void updateGameData (int round, int p1score, int p2score)
Private Attributes
GamePlayModel itsModel
AnchorPane rootPane
Circle c1
Circle c2
Circle TurnCircle
GridPane gridPane
TextField roundTextField
TextField P1Score
TextField P2Score
Detailed Description
Definition at line 22 of file BoardController.java.
Constructor & Destructor Documentation
BoardController()
sample.BoardController.BoardController ()
Definition at line 42 of file BoardController.java.
{
         itsModel = GamePlayModel.getInstance();
     }
References sample.GamePlayModel.getInstance(), and sample.BoardController.itsModel.
Member Function Documentation
cellClicked()
void sample.BoardController.cellClicked (javafx.scene.input.MouseEvent e)
Definition at line 77 of file BoardController.java.
{
         try {
             ArrayList<Node> a;
             Node source = (Node)e.getSource();
             Integer colIndex = gridPane.getColumnIndex(source);
             itsModel.ChangeStatus(colIndex);
         } catch (Exception exc) {
             System.out.println(exc);
         }
     }
References sample.GamePlayModel.ChangeStatus(), sample.BoardController.gridPane, and sample.BoardController.itsModel.
getNodeByRowColumnIndex()
Node sample.BoardController.getNodeByRowColumnIndex (Integer ColIndex, Integer RowIndex)
Definition at line 105 of file BoardController.java.
{
         Node result = null;
         ObservableList<Node> childrens = gridPane.getChildren();
         for (Node node : childrens) {
             Integer nodeRow = gridPane.getRowIndex(node);
             Integer nodeCol = gridPane.getColumnIndex(node);
             if (nodeRow == null) nodeRow = 0;
             if (nodeCol == null) nodeCol = 0;
             if(nodeRow == RowIndex && nodeCol ==ColIndex ) {
                 result = node;
                 break;
             }
         }
         return result;
     }
References sample.BoardController.gridPane.
Referenced by sample.BoardController.SETCellColor().
initialize()
void sample.BoardController.initialize ()
Definition at line 46 of file BoardController.java.
{
         if(itsModel.GETPlayer1Color() == PlayerColor.RED){
             c1.setFill(Color.RED);
             c2.setFill(Color.YELLOW);
         }else if (itsModel.GETPlayer1Color() == PlayerColor.YELLOW) {
             c1.setFill(Color.YELLOW);
             c2.setFill(Color.RED);
         }
         // Should be called before start new game to set the observer for the model
         // interface can not make objects so we implement the interface in a class that can make object
         itsModel.SETGamePlayerObserver(this);
         itsModel.StartNewGame();
     }
References sample.BoardController.c1, sample.BoardController.c2, sample.GamePlayModel.GETPlayer1Color(), sample.BoardController.itsModel, sample.PlayerColor.RED, sample.GamePlayModel.SETGamePlayerObserver(), sample.GamePlayModel.StartNewGame(), and sample.PlayerColor.YELLOW.
PrintIfWin()
void sample.BoardController.PrintIfWin () throws IOException
Implements sample.IGamePlayObserver.
Definition at line 139 of file BoardController.java.
{
         try {
             AnchorPane pane = FXMLLoader.load(getClass().getResource("PlayAgain.fxml"));
             rootPane.getChildren().setAll(pane);
         } catch (Exception e) {
             System.out.println(e);
         }
     }
References sample.BoardController.rootPane.
SETCellColor()
void sample.BoardController.SETCellColor (Integer ColIndex, Integer RowIndex, PlayerColor cellColor)
Implements sample.IGamePlayObserver.
Definition at line 126 of file BoardController.java.
{
         Node node = getNodeByRowColumnIndex(ColIndex, RowIndex);
         Circle cx = (Circle) node;
         if (cellColor == PlayerColor.RED) {
             cx.setFill(Color.RED);
         } else if (cellColor == PlayerColor.YELLOW) {
             cx.setFill(Color.YELLOW);
         } else {
             /* do nothing */
         }
     }
References sample.BoardController.getNodeByRowColumnIndex(), sample.PlayerColor.RED, and sample.PlayerColor.YELLOW.
SETIsPlayer1CurrentTurn()
void sample.BoardController.SETIsPlayer1CurrentTurn (boolean isPlayer1CurrTurn)
Implements sample.IGamePlayObserver.
Definition at line 89 of file BoardController.java.
{
         if(isPlayer1CurrTurn) {
             if(itsModel.GETPlayer1Color() == PlayerColor.RED)
                 TurnCircle.setFill(Color.RED);
             else if (itsModel.GETPlayer1Color() == PlayerColor.YELLOW)
                 TurnCircle.setFill(Color.YELLOW);
         } else {
             if(itsModel.GETPlayer1Color() == PlayerColor.RED)
                 TurnCircle.setFill(Color.YELLOW);
             else if (itsModel.GETPlayer1Color() == PlayerColor.YELLOW)
                 TurnCircle.setFill(Color.RED);
         }
     }
References sample.GamePlayModel.GETPlayer1Color(), sample.BoardController.itsModel, sample.PlayerColor.RED, sample.BoardController.TurnCircle, and sample.PlayerColor.YELLOW.
showMenu()
void sample.BoardController.showMenu (javafx.event.ActionEvent actionEvent) throws IOException
Definition at line 65 of file BoardController.java.
{
         try {
             AnchorPane pane = FXMLLoader.load(getClass().getResource("menu.fxml"));
             rootPane.getChildren().setAll(pane);
             itsModel.resetGameData();
         } catch (Exception e) {
             System.out.println(e);
         }
     }
References sample.BoardController.itsModel, sample.GamePlayModel.resetGameData(), and sample.BoardController.rootPane.
updateGameData()
void sample.BoardController.updateGameData (int round, int p1score, int p2score)
Implements sample.IGamePlayObserver.
Definition at line 149 of file BoardController.java.
{
         roundTextField.setText(String.valueOf(round));
         P1Score.setText(String.valueOf(p1score));
         P2Score.setText(String.valueOf(p2score));
     }
References sample.BoardController.P1Score, sample.BoardController.P2Score, and sample.BoardController.roundTextField.
Member Data Documentation
c1
Circle sample.BoardController.c1 private
Definition at line 28 of file BoardController.java.
Referenced by sample.BoardController.initialize().
c2
Circle sample.BoardController.c2 private
Definition at line 30 of file BoardController.java.
Referenced by sample.BoardController.initialize().
gridPane
GridPane sample.BoardController.gridPane private
Definition at line 34 of file BoardController.java.
Referenced by sample.BoardController.cellClicked(), and sample.BoardController.getNodeByRowColumnIndex().
itsModel
GamePlayModel sample.BoardController.itsModel private
Definition at line 23 of file BoardController.java.
Referenced by sample.BoardController.BoardController(), sample.BoardController.cellClicked(), sample.BoardController.initialize(), sample.BoardController.SETIsPlayer1CurrentTurn(), and sample.BoardController.showMenu().
P1Score
TextField sample.BoardController.P1Score private
Definition at line 38 of file BoardController.java.
Referenced by sample.BoardController.updateGameData().
P2Score
TextField sample.BoardController.P2Score private
Definition at line 40 of file BoardController.java.
Referenced by sample.BoardController.updateGameData().
rootPane
AnchorPane sample.BoardController.rootPane private
Definition at line 26 of file BoardController.java.
Referenced by sample.BoardController.PrintIfWin(), and sample.BoardController.showMenu().
roundTextField
TextField sample.BoardController.roundTextField private
Definition at line 36 of file BoardController.java.
Referenced by sample.BoardController.updateGameData().
TurnCircle
Circle sample.BoardController.TurnCircle private
Definition at line 32 of file BoardController.java.
Referenced by sample.BoardController.SETIsPlayer1CurrentTurn().
The documentation for this class was generated from the following file:
C:/master/PatternsUndFrameworks/playJava/src/sample/BoardController.java