playJava: sample.Main Class Reference
sample.Main Class Reference
Public Member Functions
void start (Stage primaryStage) throws Exception
Static Public Member Functions
static void main (String[] args)
Package Attributes
GamePlayModel myGamePlayModel
GameData myGameData
Detailed Description
Definition at line 12 of file Main.java.
Member Function Documentation
main()
static void sample.Main.main (String[] args) static
Definition at line 40 of file Main.java.
{
         launch(args);
     }
start()
void sample.Main.start (Stage primaryStage) throws Exception
Definition at line 18 of file Main.java.
{
         myGamePlayModel = GamePlayModel.getInstance();
         myGameData = GameData.getInstance();
         myGamePlayModel.SETItsGameDataObject(myGameData);
         myGameData.loadGameData();
         try {
             FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("welcome1.fxml"));
             Parent root1 = (Parent) fxmlLoader.load();
             Stage stage = new Stage();
             stage.initStyle(StageStyle.UNDECORATED);
             stage.setTitle("Fantastic Four Game");
             stage.setScene(new Scene(root1));
             stage.show();
         } catch (Exception e) {
             System.out.println(e);
         }
     }
References sample.GameData.getInstance(), sample.GamePlayModel.getInstance(), sample.GameData.loadGameData(), sample.Main.myGameData, sample.Main.myGamePlayModel, and sample.GamePlayModel.SETItsGameDataObject().
Member Data Documentation
myGameData
GameData sample.Main.myGameData package
Definition at line 15 of file Main.java.
Referenced by sample.Main.start().
myGamePlayModel
GamePlayModel sample.Main.myGamePlayModel package
Definition at line 14 of file Main.java.
Referenced by sample.Main.start().
The documentation for this class was generated from the following file:
C:/master/PatternsUndFrameworks/playJava/src/sample/Main.java