playJava: sample.UserOneController Class Reference
sample.UserOneController Class Reference
Public Member Functions
UserOneController ()
void showuser2 (javafx.event.ActionEvent actionEvent) throws IOException
void chooseRed (javafx.event.ActionEvent actionEvent)
void chooseYellow (javafx.event.ActionEvent actionEvent)
Private Attributes
AnchorPane rootPane
GamePlayModel itsModel
Detailed Description
Definition at line 8 of file UserOneController.java.
Constructor & Destructor Documentation
UserOneController()
sample.UserOneController.UserOneController ()
Definition at line 14 of file UserOneController.java.
{
         itsModel = GamePlayModel.getInstance();
     }
References sample.GamePlayModel.getInstance(), and sample.UserOneController.itsModel.
Member Function Documentation
chooseRed()
void sample.UserOneController.chooseRed (javafx.event.ActionEvent actionEvent)
Definition at line 27 of file UserOneController.java.
{
         itsModel.SETPlayer1Color(PlayerColor.RED);
     }
References sample.UserOneController.itsModel, sample.PlayerColor.RED, and sample.GamePlayModel.SETPlayer1Color().
chooseYellow()
void sample.UserOneController.chooseYellow (javafx.event.ActionEvent actionEvent)
Definition at line 32 of file UserOneController.java.
{
         itsModel.SETPlayer1Color(PlayerColor.YELLOW);
     }
References sample.UserOneController.itsModel, sample.GamePlayModel.SETPlayer1Color(), and sample.PlayerColor.YELLOW.
showuser2()
void sample.UserOneController.showuser2 (javafx.event.ActionEvent actionEvent) throws IOException
Definition at line 18 of file UserOneController.java.
{
         try {
             AnchorPane pane = FXMLLoader.load(getClass().getResource("user2.fxml"));
             rootPane.getChildren().setAll(pane);
         } catch (Exception e) {
             System.out.println(e);
         }
     }
References sample.UserOneController.rootPane.
Member Data Documentation
itsModel
GamePlayModel sample.UserOneController.itsModel private
Definition at line 11 of file UserOneController.java.
Referenced by sample.UserOneController.chooseRed(), sample.UserOneController.chooseYellow(), and sample.UserOneController.UserOneController().
rootPane
AnchorPane sample.UserOneController.rootPane private
Definition at line 10 of file UserOneController.java.
Referenced by sample.UserOneController.showuser2().
The documentation for this class was generated from the following file:
C:/master/PatternsUndFrameworks/playJava/src/sample/UserOneController.java